// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: engine/v1/EngineService.proto

package enginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_engine_v1_EngineService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_EngineService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_EngineService_proto_rawDescGZIP(), []int{0}
}

type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_engine_v1_EngineService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_EngineService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_EngineService_proto_rawDescGZIP(), []int{1}
}

var File_engine_v1_EngineService_proto protoreflect.FileDescriptor

const file_engine_v1_EngineService_proto_rawDesc = "" +
	"\n" +
	"\x1dengine/v1/EngineService.proto\x12\tengine.v1\"\x16\n" +
	"\x14StartWorkflowRequest\"\x17\n" +
	"\x15StartWorkflowResponse2c\n" +
	"\rEngineService\x12R\n" +
	"\rStartWorkflow\x12\x1f.engine.v1.StartWorkflowRequest\x1a .engine.v1.StartWorkflowResponseB2Z0github.com/you/myengine/proto/engine/v1;enginev1b\x06proto3"

var (
	file_engine_v1_EngineService_proto_rawDescOnce sync.Once
	file_engine_v1_EngineService_proto_rawDescData []byte
)

func file_engine_v1_EngineService_proto_rawDescGZIP() []byte {
	file_engine_v1_EngineService_proto_rawDescOnce.Do(func() {
		file_engine_v1_EngineService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_v1_EngineService_proto_rawDesc), len(file_engine_v1_EngineService_proto_rawDesc)))
	})
	return file_engine_v1_EngineService_proto_rawDescData
}

var file_engine_v1_EngineService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_engine_v1_EngineService_proto_goTypes = []any{
	(*StartWorkflowRequest)(nil),  // 0: engine.v1.StartWorkflowRequest
	(*StartWorkflowResponse)(nil), // 1: engine.v1.StartWorkflowResponse
}
var file_engine_v1_EngineService_proto_depIdxs = []int32{
	0, // 0: engine.v1.EngineService.StartWorkflow:input_type -> engine.v1.StartWorkflowRequest
	1, // 1: engine.v1.EngineService.StartWorkflow:output_type -> engine.v1.StartWorkflowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_engine_v1_EngineService_proto_init() }
func file_engine_v1_EngineService_proto_init() {
	if File_engine_v1_EngineService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_v1_EngineService_proto_rawDesc), len(file_engine_v1_EngineService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_v1_EngineService_proto_goTypes,
		DependencyIndexes: file_engine_v1_EngineService_proto_depIdxs,
		MessageInfos:      file_engine_v1_EngineService_proto_msgTypes,
	}.Build()
	File_engine_v1_EngineService_proto = out.File
	file_engine_v1_EngineService_proto_goTypes = nil
	file_engine_v1_EngineService_proto_depIdxs = nil
}
